### ISSUE TITLE
How to get around `(iokit/common) unsupported function`?

### ISSUE THREAD

**Issue by brandonros** [guoxuzan/IOKit#1]
I've got IOKit compiled for iOS13.2 running on an iPhone. I'm able to connect a `Lightning to USB Camera Adapter` to the phone, then plug a USB device in. The device is detected and listed as a `IOUSBHostDevice` with the correct `IOUSBHostInterface`s listed, but as soon as `IOServiceOpen` is called against the device (even to just get the productId/vendorId), it fails.

Any advice?

**Comment by guoxuzan** [comment]
This is the official documentation for IOKit.

**Comment by guoxuzan** [comment]
https://developer.apple.com/documentation/iokit?language=objc

**Comment by guoxuzan** [comment]
This is the official documentation for IOKit.
https://developer.apple.com/documentation/iokit?language=objc
